Repository 4201VitruvianBots/ChargedUp2023, pull requests merged in 2023-01, with the labels that each got.

#50 Finished basic elevator code
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/elevator/IncrementElevatorHeight.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision

#59 Added shuffleboard values for elevator
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision

#64 Vision Network Table implementation
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Vision.java
Labels: ElevatorVision

#69 Elevator simulation "works", bugs still need to be fixed
  simgui-ds.json
  simgui.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/elevator/IncrementElevatorHeight.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision

#71 68 LED command
  src/main/java/frc/robot/commands/led/ledstate.java
Labels: EndgameLED

#86 Xbox Joystick and Comments
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/elevator/IncrementElevatorHeight.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision

#96 Vision Subsystem
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/auto/BlueBottomConeCubeNoBalance.java
  src/main/java/frc/robot/commands/auto/BlueMiddleTwoConeBottomBalance.java
  src/main/java/frc/robot/commands/auto/BlueMiddleTwoConeNoBalance.java
  src/main/java/frc/robot/commands/auto/BlueTopConeCubeBalance.java
  src/main/java/frc/robot/commands/auto/BlueTopTwoConeBalance.java
  src/main/java/frc/robot/simulation/FieldSim.java
  src/main/java/frc/robot/subsystems/SwerveDrive.java
  src/main/java/frc/robot/subsystems/SwerveModule.java
  src/main/java/frc/robot/subsystems/Vision.java
Labels: ElevatorVision

#123 Added field constants and updated dimensions
  src/main/java/frc/robot/simulation/SimConstants.java
Labels: miscellaneous

#125 Added Mech2d visualization
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision

#127 BotPose
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/simulation/FieldSim.java
  src/main/java/frc/robot/subsystems/Vision.java
Labels: ElevatorVision

#130 Added memory log artifact
  .github/artifacts/memorylog.txt
  .github/workflows/memoryleaktest.yml
  .gitignore
  README.md
  src/main/java/frc/robot/simulation/MemoryLog.java
Labels: miscellaneous

#135 104 Add motion magic/PID to elevator
  .github/artifacts/memorylog.txt
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/elevator/IncrementElevatorHeight.java
  src/main/java/frc/robot/commands/elevator/MoveToElevatorHeight.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: ElevatorVision
